### PR TITLE
fix(hardhat-polkadot-node): enable docker for tests

### LINKED ISSUE #147: feature : add pre-built binaries for nodeConfig and adapterConfig
#### 📝 Description

```
 networks: {
    hardhat: {
      polkavm: true,
      nodeConfig: {
        nodeBinaryPath: 'INSERT_PATH_TO_SUBSTRATE_NODE',
        rpcPort: 8000,
        dev: true,
      },
      adapterConfig: {
        adapterBinaryPath: 'INSERT_PATH_TO_ETH_RPC_ADAPTER',
        dev: true,
      },
    },
```

#### 🤔 Motivation

Can we not pre built and store it somewhere so the devs can easily download or fetch from somwhere and give the path?
building the binaries is a tedious job 😓

### PR DESCRIPTION
**Pull request by bee344**
### Description
This facilitates using Docker to run a local node and tests without providing the node and adapter configurations.

example:
```ts
import { HardhatUserConfig } from "hardhat/config"
import "@nomicfoundation/hardhat-toolbox"
import "@parity/hardhat-polkadot"
import "@parity/hardhat-polkadot-resolc"

const config: HardhatUserConfig = {
    solidity: "0.8.28",
    networks: {
        hardhat: {
            polkavm: true,
        },
    },
}

export default config
```

This also avoids using hardcoded image tags and always uses the last updated one.

Also changes endpoint to `0.0.0.0` for docker server in order to work internally.

Closes #147

### CODE REVIEW

File: packages/hardhat-polkadot-node/src/servers/docker-server.ts [hunk 1]
```diff
@@ -43,6 +44,10 @@ export class DockerRpcServer implements RpcServer {
         adapterArgs: string[] = [],
         blockProcess: boolean = true,
     ): Promise<void> {
+        // Here we avoid hardcoding the images in order to always use the latest available one.
+        const nodeImageTag = await getLatestImageName(NODE_CONTAINER_NAME)
+        const adapterImageTag = await getLatestImageName(ADAPTER_CONTAINER_NAME)
```
Comment (BigTava) [inline packages/hardhat-polkadot-node/src/servers/docker-server.ts:49]: Yes, but this is running in every command. What if we use some caching flag?

**Review by BigTava — CHANGES_REQUESTED** [review]

**Review by BigTava — APPROVED** [review]
LFG
